declare module "@radix-ui/react-accordion"
declare module "*.scss"
declare module "framer-motion"

declare module "next/server"

declare module "next-sanity/studio"
declare module "@sanity/icons"
declare module "sanity"
declare module "sanity/structure"
declare module "next-sanity"
declare module "react-use-measure"
declare module "resend"
declare module "@react-email/components"
declare module "@react-email/render"
declare module "react-cookiebot"
